name: Publish Web Demo

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    - name: Deploy to GitHub Pages
      uses: bluefireteam/flutter-gh-pages@v7
      with:
        workingDir: example
        baseHref: /timeline_list/